### ISSUE TITLE
The script should retry after 'Lost connection to MySQL server' error

### ISSUE THREAD

**Issue by framawiki** [Niharika29/database-reports#15]
```
Wikipedia:Rapports/Mod&egrave;les inclus sur le plus grand nombre de pages
orphaned_talk
Wikipedia:Rapports/Pages de discussion orphelines
unused_templates
Wikipedia:Rapports/Mod&egrave;les inutilis&eacute;s
article_by_size
Wikipedia:Rapports/Articles par taille
most_edited_page_last_month
Traceback (most recent call last):
  File "/shared/pywikipedia/core/pwb.py", line 263, in <module>
    if not main():
  File "/shared/pywikipedia/core/pwb.py", line 256, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "/shared/pywikipedia/core/pwb.py", line 121, in run_python_file
    main_mod.__dict__)
  File "main.py", line 69, in <module>
    main(sys.argv)
  File "main.py", line 17, in main
    method()
  File "main.py", line 63, in most_edited_page_last_month
    self.rep.most_edited_page_last_month()
  File "reports.py", line 375, in most_edited_page_last_month
    cur.execute( query )
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
CRITICAL: Closing network session.
Network session closed.
<class '_mysql_exceptions.OperationalError'>
```

**Comment by ritikBhandari** [comment]
Is this issue still open?
I would like to work on this if possible.

**Comment by MusikAnimal** [comment]
In theory, it could be still be an issue, but the new Toolforge replica servers have remarkably good performance compared to those used back in 2017. I'm not aware of queries timing out anymore (in this case it didn't time out exactly, but the _connection_ timed out following a long-running query such that new queries couldn't be ran). So I would say a fix for this issue is purely optional at this point.

**Comment by ritikBhandari** [comment]
Oh okay. Thanks
